# Generated by Django 4.2.16 on 2025-11-06 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=200)),
                ('channel_id', models.CharField(blank=True, max_length=200, null=True)),
                ('post_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('big_text', models.TextField(blank=True, null=True)),
                ('sub_text', models.CharField(blank=True, max_length=500, null=True)),
                ('summary_text', models.CharField(blank=True, max_length=500, null=True)),
                ('info_text', models.CharField(blank=True, max_length=500, null=True)),
                ('text_lines', models.TextField(blank=True, null=True)),
                ('large_icon_base64', models.TextField(blank=True, null=True)),
                ('picture_base64', models.TextField(blank=True, null=True)),
                ('conversation_title', models.CharField(blank=True, max_length=500, null=True)),
                ('people', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timestamp_opened', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=200, null=True)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('message_time', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Notifications.notifications')),
            ],
        ),
    ]
