# Generated by Django 4.2.16 on 2025-11-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AddField(
            model_name='notifications',
            name='timestamp_dismissed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
