# Generated by Django 4.2.16 on 2026-03-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationstate',
            name='is_bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
